services:
  - type: web
    name: splitreceipt-frontend
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: cd frontend && npm install && npx prisma generate && npm run build
    startCommand: cd frontend && npx prisma migrate deploy && npx prisma generate && npx next start -p $PORT
    autoDeploy: true
    healthCheckPath: /api/health-db
    envVars:
      - key: NODE_ENV
        value: production
    disk: 1024
